import React from "react";

const TermsAndConditions = () => {
  return (
    <div className="bg-gray-100 min-h-screen">
      <div className="px-6 md:px-20 lg:px-32 xl:px-40 py-10">
        <div className="max-w-4xl mx-auto text-gray-700 text-sm leading-7 space-y-6">
          <h1 className="text-lg font-semibold text-gray-900">
            TERMS AND CONDITIONS
          </h1>
          <p>
            This document is an electronic record in terms of the Information
            Technology Act, 2000 and rules made thereunder, as applicable, and
            the amended provisions pertaining to electronic records in various
            statutes as amended by the Information Technology Act, 2000. This
            electronic record is generated by a computer system and does not
            require any physical or digital signatures.
          </p>

          <p>
            This document is published in accordance with the provisions of Rule
            3 (1) of the Information Technology (Guidelines for Intermediaries
            and Digital Media Ethics Code) Rules, 2021 that require publishing
            the rules and regulations, privacy policy and Terms of Use for
            access or usage of the platform.
          </p>

          {/* SECTION 1 */}
          <h2 className="font-semibold text-gray-900 text-base">
            1. Terms of Use
          </h2>

          <p>
            These Terms of Use ("Terms") govern your access to and use of the
            platform operated by Bengol Spices Pvt. Ltd. ("Company", "we",
            "our", or "us"). By accessing or using our platform, you agree to be
            bound by these Terms and all applicable policies, including but not
            limited to the Privacy Policy and Cancellation & Refund Policy.
          </p>

          <p>
            If you do not agree to these Terms, you must not access or use the
            platform. Continued use of the platform signifies your acceptance of
            any updates or modifications to these Terms.
          </p>

          {/* SECTION 2 */}
          <h2 className="font-semibold text-gray-900 text-base">
            2. Nature of Business
          </h2>

          <p>
            Bengol Spices Pvt. Ltd. is engaged in the business of retail and
            wholesale distribution of spices. The platform facilitates the
            ordering of products by registered agents, which are subsequently
            processed, packed, and delivered to retail stores and business
            partners through authorized delivery personnel.
          </p>

          <p>
            The Company acts as an intermediary platform connecting agents,
            retailers, and delivery partners, ensuring efficient supply chain
            management and timely distribution of goods.
          </p>

          {/* SECTION 3 */}
          <h2 className="font-semibold text-gray-900 text-base">
            3. User Eligibility
          </h2>

          <p>
            You must be at least 18 years of age and legally capable of entering
            into binding contracts to use this platform. By using the platform,
            you represent and warrant that you meet these eligibility
            requirements.
          </p>

          {/* SECTION 4 */}
          <h2 className="font-semibold text-gray-900 text-base">
            4. Account Registration
          </h2>

          <p>
            To access certain features of the platform, users may be required to
            register and create an account. You agree to provide accurate,
            complete, and up-to-date information during registration and to
            update such information as necessary.
          </p>

          <p>
            You are responsible for maintaining the confidentiality of your
            account credentials and for all activities that occur under your
            account.
          </p>

          {/* SECTION 5 */}
          <h2 className="font-semibold text-gray-900 text-base">
            5. Orders and Fulfillment
          </h2>

          <p>
            All orders placed through the platform are subject to acceptance and
            availability. The Company reserves the right to refuse or cancel any
            order at its discretion.
          </p>

          <p>
            Delivery timelines are indicative and may vary based on operational,
            logistical, or external factors. The Company shall not be held
            liable for delays beyond its reasonable control.
          </p>

          {/* SECTION 6 */}
          <h2 className="font-semibold text-gray-900 text-base">
            6. Pricing and Payments
          </h2>

          <p>
            All prices listed on the platform are subject to change without
            prior notice. Payments must be made through approved payment methods
            as specified on the platform.
          </p>

          <p>
            The Company reserves the right to modify pricing, discounts, and
            offers at any time without prior notice.
          </p>

          {/* SECTION 7 */}
          <h2 className="font-semibold text-gray-900 text-base">
            7. User Responsibilities
          </h2>

          <p>
            Users agree not to misuse the platform or engage in any activity
            that disrupts or interferes with the functioning of the platform.
            Any fraudulent, abusive, or unlawful activity may result in
            suspension or termination of access.
          </p>

          {/* SECTION 8 */}
          <h2 className="font-semibold text-gray-900 text-base">
            8. Intellectual Property
          </h2>

          <p>
            All content, trademarks, logos, and intellectual property displayed
            on the platform are the property of Bengol Spices Pvt. Ltd. and are
            protected by applicable laws. Unauthorized use is strictly
            prohibited.
          </p>

          {/* SECTION 9 */}
          <h2 className="font-semibold text-gray-900 text-base">
            9. Limitation of Liability
          </h2>

          <p>
            The Company shall not be liable for any indirect, incidental,
            special, or consequential damages arising out of or in connection
            with the use of the platform.
          </p>

          <p>
            The platform is provided on an "as is" and "as available" basis
            without warranties of any kind, either express or implied.
          </p>

          {/* SECTION 10 */}
          <h2 className="font-semibold text-gray-900 text-base">
            10. Termination
          </h2>

          <p>
            The Company reserves the right to suspend or terminate user access
            to the platform at any time, without prior notice, for conduct that
            violates these Terms or is harmful to other users or the business.
          </p>

          {/* SECTION 11 */}
          <h2 className="font-semibold text-gray-900 text-base">
            11. Governing Law
          </h2>

          <p>
            These Terms shall be governed by and construed in accordance with
            the laws of India. Any disputes arising shall be subject to the
            exclusive jurisdiction of the courts located in India.
          </p>

          {/* SECTION 12 */}
          <h2 className="font-semibold text-gray-900 text-base">
            12. Changes to Terms
          </h2>

          <p>
            The Company reserves the right to update or modify these Terms at
            any time without prior notice. Continued use of the platform after
            such changes constitutes acceptance of the revised Terms.
          </p>
        </div>
      </div>
    </div>
  );
};

export default TermsAndConditions;
